version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oblige-connect"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kt1z7fgjvqio"
s3_prefix = "oblige-connect"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
